In [1]:
import sys
from pathlib import Path

import pandas as pd

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.data_loader import download_market_data

In [2]:
portfolio_assets = [
    "AAPL",  # Apple
    "JPM",   # JPMorgan Chase
    "JNJ",   # Johnson & Johnson
    "KO",    # Coca-Cola
    "XOM",   # Exxon Mobil
    "GLD",   # Gold ETF
    "TLT"    # Long-Term Treasury Bond ETF
]

benchmark = "SPY"

tickers = portfolio_assets + [benchmark]

tickers

['AAPL', 'JPM', 'JNJ', 'KO', 'XOM', 'GLD', 'TLT', 'SPY']

In [3]:
from datetime import date

start_date = "2016-01-01"
end_date = date.today().strftime("%Y-%m-%d")

print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")

Start Date: 2016-01-01
End Date: 2026-07-21

In [4]:
market_data = download_market_data(
    tickers=tickers,
    start_date=start_date,
    end_date=end_date
    )

In [5]:
market_data.head()

Ticker             KO                                                    GLD  \
Price            Open       High        Low      Close    Volume        Open
Date
2016-01-04  30.512738  30.628044  30.246095  30.555979  16084100  103.129997
2016-01-05  30.491108  30.721718  30.390213  30.664064  15781900  103.129997
2016-01-06  30.411843  30.635246  30.296538  30.498322  16245100  104.370003
2016-01-07  30.015474  30.346977  29.871342  29.993853  20563600  105.830002
2016-01-08  30.015472  30.354180  29.842513  29.914577  14645900  105.480003

Ticker                                                    ...        JPM  \
Price             High         Low       Close    Volume  ...       Open
Date                                                      ...
2016-01-04  103.669998  102.489998  102.889999   6440000  ...  48.434009
2016-01-05  103.459999  102.930000  103.180000   3500300  ...  48.244659
2016-01-06  104.800003  103.930000  104.669998   9316600  ...  47.502439
2016-01-07  106.239998  105.190002  106.150002  11730400  ...  46.548142
2016-01-08  105.800003  105.040001  105.680000   7678200  ...  46.298209

Ticker                                                       JNJ             \
Price            High        Low      Close    Volume       Open       High
Date
2016-01-04  48.517318  47.722076  48.184074  25393200  76.259777  76.334753
2016-01-05  48.570327  47.744793  48.267380  16566700  75.412545  76.057354
2016-01-06  47.812962  47.214636  47.570602  22961500  74.842693  75.704937
2016-01-07  46.957125  45.502970  45.646870  27630900  74.460322  75.045147
2016-01-08  46.404241  44.571397  44.624413  22373300  74.887656  74.932646

Ticker
Price             Low      Close    Volume
Date
2016-01-04  74.565280  75.337555  12722800
2016-01-05  75.405046  75.652473   6467200
2016-01-06  74.677741  75.270065   7733800
2016-01-07  74.137918  74.392845   9433100
2016-01-08  73.365611  73.598045   9766700

[5 rows x 40 columns]

In [6]:
market_data.columns

MultiIndex([(  'KO',   'Open'),
            (  'KO',   'High'),
            (  'KO',    'Low'),
            (  'KO',  'Close'),
            (  'KO', 'Volume'),
            ( 'GLD',   'Open'),
            ( 'GLD',   'High'),
            ( 'GLD',    'Low'),
            ( 'GLD',  'Close'),
            ( 'GLD', 'Volume'),
            ('AAPL',   'Open'),
            ('AAPL',   'High'),
            ('AAPL',    'Low'),
            ('AAPL',  'Close'),
            ('AAPL', 'Volume'),
            ( 'TLT',   'Open'),
            ( 'TLT',   'High'),
            ( 'TLT',    'Low'),
            ( 'TLT',  'Close'),
            ( 'TLT', 'Volume'),
            ( 'SPY',   'Open'),
            ( 'SPY',   'High'),
            ( 'SPY',    'Low'),
            ( 'SPY',  'Close'),
            ( 'SPY', 'Volume'),
            ( 'XOM',   'Open'),
            ( 'XOM',   'High'),
            ( 'XOM',    'Low'),
            ( 'XOM',  'Close'),
            ( 'XOM', 'Volume'),
            ( 'JPM',   'Open'),
            ( 'JPM',   'High'),
            ( 'JPM',    'Low'),
            ( 'JPM',  'Close'),
            ( 'JPM', 'Volume'),
            ( 'JNJ',   'Open'),
            ( 'JNJ',   'High'),
            ( 'JNJ',    'Low'),
            ( 'JNJ',  'Close'),
            ( 'JNJ', 'Volume')],
           names=['Ticker', 'Price'])

In [7]:
market_data.columns.levels

FrozenList([['AAPL', 'GLD', 'JNJ', 'JPM', 'KO', 'SPY', 'TLT', 'XOM'], ['Close', 'High', 'Low', 'Open', 'Volume']])

In [8]:
market_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2650 entries, 2016-01-04 to 2026-07-20
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (KO, Open)      2650 non-null   float64
 1   (KO, High)      2650 non-null   float64
 2   (KO, Low)       2650 non-null   float64
 3   (KO, Close)     2650 non-null   float64
 4   (KO, Volume)    2650 non-null   int64
 5   (GLD, Open)     2650 non-null   float64
 6   (GLD, High)     2650 non-null   float64
 7   (GLD, Low)      2650 non-null   float64
 8   (GLD, Close)    2650 non-null   float64
 9   (GLD, Volume)   2650 non-null   int64
 10  (AAPL, Open)    2650 non-null   float64
 11  (AAPL, High)    2650 non-null   float64
 12  (AAPL, Low)     2650 non-null   float64
 13  (AAPL, Close)   2650 non-null   float64
 14  (AAPL, Volume)  2650 non-null   int64
 15  (TLT, Open)     2650 non-null   float64
 16  (TLT, High)     2650 non-null   float64
 17  (TLT, Low)      2650 non-null   float64
 18  (TLT, Close)    2650 non-null   float64
 19  (TLT, Volume)   2650 non-null   int64
 20  (SPY, Open)     2650 non-null   float64
 21  (SPY, High)     2650 non-null   float64
 22  (SPY, Low)      2650 non-null   float64
 23  (SPY, Close)    2650 non-null   float64
 24  (SPY, Volume)   2650 non-null   int64
 25  (XOM, Open)     2650 non-null   float64
 26  (XOM, High)     2650 non-null   float64
 27  (XOM, Low)      2650 non-null   float64
 28  (XOM, Close)    2650 non-null   float64
 29  (XOM, Volume)   2650 non-null   int64
 30  (JPM, Open)     2650 non-null   float64
 31  (JPM, High)     2650 non-null   float64
 32  (JPM, Low)      2650 non-null   float64
 33  (JPM, Close)    2650 non-null   float64
 34  (JPM, Volume)   2650 non-null   int64
 35  (JNJ, Open)     2650 non-null   float64
 36  (JNJ, High)     2650 non-null   float64
 37  (JNJ, Low)      2650 non-null   float64
 38  (JNJ, Close)    2650 non-null   float64
 39  (JNJ, Volume)   2650 non-null   int64
dtypes: float64(32), int64(8)
memory usage: 848.8 KB

In [9]:
close_prices = market_data.xs("Close", level=1, axis=1)
close_prices.head()

Ticker,KO,GLD,AAPL,TLT,SPY,XOM,JPM,JNJ
Date,,,,,,,,
2016-01-04,30.555979,102.889999,23.709105,90.649826,169.471558,49.319614,48.184074,75.337555
2016-01-05,30.664064,103.180000,23.114969,90.284065,169.758209,49.739841,48.267380,75.652473
2016-01-06,30.498322,104.669998,22.662621,91.500656,167.616791,49.325985,47.570602,75.270065
2016-01-07,29.993853,106.150002,21.706150,91.664871,163.595444,48.536449,45.646870,74.392845
2016-01-08,29.914577,105.680000,21.820929,92.075447,161.799698,47.555923,44.624413,73.598045

In [11]:
close_prices.shape

(2650, 8)

In [14]:
close_prices.isnull().sum()

Ticker
KO      0
GLD     0
AAPL    0
TLT     0
SPY     0
XOM     0
JPM     0
JNJ     0
dtype: int64

In [16]:
close_prices.describe()

Ticker,KO,GLD,AAPL,TLT,SPY,XOM,JPM,JNJ
count,2650.000000,2650.000000,2650.000000,2650.000000,2650.000000,2650.000000,2650.000000,2650.000000
mean,48.246565,184.269989,122.453957,100.103920,370.706475,73.482300,134.681529,133.961352
std,13.324197,81.566656,80.050931,16.127756,154.010488,30.304721,74.531592,34.780433
min,29.820904,102.889999,20.565859,73.702705,154.161606,23.823561,40.193787,71.791115
25%,35.964251,124.089998,42.637192,87.120800,241.667664,52.666672,84.725403,107.570091
50%,46.542974,166.580002,126.893196,95.658577,359.152481,57.579916,112.111580,138.063553
75%,56.839992,187.332497,180.504566,111.595432,442.960602,100.200951,150.457973,150.269836
max,84.919998,495.899994,333.739990,142.699570,757.618225,170.313995,346.910004,267.239990

In [18]:
from pathlib import Path

processed_path = project_root / "data" / "processed"
processed_path.mkdir(parents=True, exist_ok=True)

close_prices.to_csv(processed_path / "close_prices.csv")

print("Saved successfully!")

Saved successfully!

In [19]:
processed_path

WindowsPath('c:/Users/Sahiti Putcha/Documents/Equity-Risk-Portfolio-Analysis/data/processed')